Version 0.0.2

---
Name: Production2013
Base: Robot
Children:
- Name: Subsystems
  Base: Subsystems
  Children:
  - Name: DriveTrain
    Base: Subsystem
    Children:
    - Name: RobotDrive
      Base: Robot Drive 2
      Children:
      - Name: DriveLeft
        Base: Speed Controller
        Children: []
        Properties:
          Output Module (Digital): !!robotbuilder.data.properties.ChoicesProperty
            choices: &id001 ['1', '2']
            default: '1'
            name: Output Module (Digital)
            validators: &id002 [PWMOutput]
            value: '1'
          Type: !!robotbuilder.data.properties.ChoicesProperty
            choices: &id003 [Victor, Jaguar, Talon]
            default: Victor
            name: Type
            validators: null
            value: Victor
          Output Channel (PWM): !!robotbuilder.data.properties.ChoicesProperty
            choices: &id004 ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']
            default: '1'
            name: Output Channel (PWM)
            validators: &id005 [PWMOutput]
            value: '1'
      - Name: DriveRight
        Base: Speed Controller
        Children: []
        Properties:
          Output Module (Digital): !!robotbuilder.data.properties.ChoicesProperty
            choices: *id001
            default: '1'
            name: Output Module (Digital)
            validators: *id002
            value: '1'
          Type: !!robotbuilder.data.properties.ChoicesProperty
            choices: *id003
            default: Victor
            name: Type
            validators: null
            value: Victor
          Output Channel (PWM): !!robotbuilder.data.properties.ChoicesProperty
            choices: *id004
            default: '1'
            name: Output Channel (PWM)
            validators: *id005
            value: '2'
      Properties:
        Sensitivity: !!robotbuilder.data.properties.DoubleProperty {default: 0.5,
          name: Sensitivity, validators: null, value: 0.5}
        Safety Enabled: !!robotbuilder.data.properties.BooleanProperty {default: true,
          name: Safety Enabled, validators: null, value: true}
        Left Motor Inverted: !!robotbuilder.data.properties.BooleanProperty {default: false,
          name: Left Motor Inverted, validators: null, value: false}
        Right Motor: !!robotbuilder.data.properties.ChildSelectionProperty
          default: 1
          name: Right Motor
          type: PIDOutput
          validators: [RobotDrive2, ChildDropdownSelected]
          value: DriveTrain DriveRight
        Maximum Output: !!robotbuilder.data.properties.DoubleProperty {default: 1,
          name: Maximum Output, validators: null, value: 1.0}
        Left Motor: !!robotbuilder.data.properties.ChildSelectionProperty
          default: 0
          name: Left Motor
          type: PIDOutput
          validators: [RobotDrive2, ChildDropdownSelected]
          value: DriveTrain DriveLeft
        Right Motor Inverted: !!robotbuilder.data.properties.BooleanProperty {default: false,
          name: Right Motor Inverted, validators: null, value: false}
        Safety Expiration Time: !!robotbuilder.data.properties.DoubleProperty {default: 0.1,
          name: Safety Expiration Time, validators: null, value: 0.1}
    Properties:
      Default Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Default Command, type: Command, validators: null, value: None}
  - Name: Shooter
    Base: Subsystem
    Children:
    - Name: ShooterMotor
      Base: CAN Jaguar
      Children: []
      Properties:
        CAN ID: !!robotbuilder.data.properties.ChoicesProperty
          choices: ['2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12']
          default: '2'
          name: CAN ID
          validators: [CANID]
          value: '2'
    Properties:
      Default Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Default Command, type: Command, validators: null, value: None}
  - Name: Feeder
    Base: Subsystem
    Children: []
    Properties:
      Default Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Default Command, type: Command, validators: null, value: None}
  - Name: Climber
    Base: Subsystem
    Children:
    - Name: ClimberMotor
      Base: Speed Controller
      Children: []
      Properties:
        Output Module (Digital): !!robotbuilder.data.properties.ChoicesProperty
          choices: *id001
          default: '1'
          name: Output Module (Digital)
          validators: *id002
          value: '1'
        Type: !!robotbuilder.data.properties.ChoicesProperty
          choices: *id003
          default: Victor
          name: Type
          validators: null
          value: Victor
        Output Channel (PWM): !!robotbuilder.data.properties.ChoicesProperty
          choices: *id004
          default: '1'
          name: Output Channel (PWM)
          validators: *id005
          value: '3'
    - Name: TapeLimitLeft
      Base: Limit Switch
      Children: []
      Properties:
        Input Channel (Digital): !!robotbuilder.data.properties.ChoicesProperty
          choices: &id006 ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11',
            '12', '13', '14']
          default: '1'
          name: Input Channel (Digital)
          validators: &id007 [DigitalChannel]
          value: '1'
        Input Module (Digital): !!robotbuilder.data.properties.ChoicesProperty
          choices: &id008 ['1', '2']
          default: '1'
          name: Input Module (Digital)
          validators: &id009 [DigitalChannel]
          value: '1'
    - Name: TapeLimitRight
      Base: Limit Switch
      Children: []
      Properties:
        Input Channel (Digital): !!robotbuilder.data.properties.ChoicesProperty
          choices: *id006
          default: '1'
          name: Input Channel (Digital)
          validators: *id007
          value: '2'
        Input Module (Digital): !!robotbuilder.data.properties.ChoicesProperty
          choices: *id008
          default: '1'
          name: Input Module (Digital)
          validators: *id009
          value: '1'
    - Name: TapeAngleLeft
      Base: Servo
      Children: []
      Properties:
        Output Module (Digital): !!robotbuilder.data.properties.ChoicesProperty
          choices: &id010 ['1', '2']
          default: '1'
          name: Output Module (Digital)
          validators: &id011 [PWMOutput]
          value: '1'
        Output Channel (PWM): !!robotbuilder.data.properties.ChoicesProperty
          choices: &id012 ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']
          default: '1'
          name: Output Channel (PWM)
          validators: &id013 [PWMOutput]
          value: '4'
    - Name: TapeAngleRight
      Base: Servo
      Children: []
      Properties:
        Output Module (Digital): !!robotbuilder.data.properties.ChoicesProperty
          choices: *id010
          default: '1'
          name: Output Module (Digital)
          validators: *id011
          value: '1'
        Output Channel (PWM): !!robotbuilder.data.properties.ChoicesProperty
          choices: *id012
          default: '1'
          name: Output Channel (PWM)
          validators: *id013
          value: '5'
    Properties:
      Default Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Default Command, type: Command, validators: null, value: None}
  Properties: {}
- Name: Operator Interface
  Base: OI
  Children:
  - Name: DriveStick
    Base: Joystick
    Children: []
    Properties:
      Number: !!robotbuilder.data.properties.ChoicesProperty
        choices: &id014 ['1', '2', '3', '4']
        default: 1
        name: Number
        validators: &id015 [Joystick]
        value: '1'
  - Name: CCiBoard
    Base: Joystick
    Children: []
    Properties:
      Number: !!robotbuilder.data.properties.ChoicesProperty
        choices: *id014
        default: 1
        name: Number
        validators: *id015
        value: '2'
  Properties: {}
- Name: Commands
  Base: Commands
  Children:
  - Name: Autonomous Command
    Base: Command
    Children: []
    Properties:
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: None}
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: true}
  - Name: DriveWithJoystick
    Base: Command
    Children: []
    Properties:
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: DriveTrain}
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: false}
  - Name: Shoot
    Base: Command
    Children: []
    Properties:
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: Shooter}
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: true}
  - Name: Climb
    Base: Command
    Children: []
    Properties:
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: Climber}
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: false}
  - Name: Feed
    Base: Command
    Children: []
    Properties:
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: Feeder}
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: true}
  Properties: {}
Properties:
  Autonomous Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
    name: Autonomous Command, type: Command, validators: null, value: Autonomous Command}
  Wiring File: !!robotbuilder.data.properties.FileProperty {default: '', extension: html,
    folder: false, name: Wiring File, validators: null, value: 'C:\WindRiver\workspace\Production2013\RobotBuilder\Production2013.html'}
  C++ Windriver Workspace: !!robotbuilder.data.properties.FileProperty {default: 'C:\Windriver\workspace',
    extension: null, folder: true, name: C++ Windriver Workspace, validators: null,
    value: 'C:\Windriver\workspace'}
  Use Default Java Package: !!robotbuilder.data.properties.BooleanProperty {default: true,
    name: Use Default Java Package, validators: null, value: true}
  Java Package: !!robotbuilder.data.properties.StringProperty {default: org.usfirst.frc0000,
    name: Java Package, validators: null, value: org.usfirst.frc0000}
  Export Subsystems: !!robotbuilder.data.properties.BooleanProperty {default: true,
    name: Export Subsystems, validators: null, value: true}
  Team Number: !!robotbuilder.data.properties.IntegerProperty {default: 0, name: Team Number,
    validators: null, value: 1388}
  Export Commands: !!robotbuilder.data.properties.BooleanProperty {default: true,
    name: Export Commands, validators: null, value: true}
  Java Project Directory: !!robotbuilder.data.properties.FileProperty {default: 'C:\Users\Davey\NetBeansProjects',
    extension: null, folder: true, name: Java Project Directory, validators: null,
    value: 'C:\Users\Davey\NetBeansProjects'}
